apiVersion: apps/v1
kind: Deployment
metadata:
  name: blablabla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      annotations:
        "profefe.com/enable": "true"
        "profefe.com/port": "9999"
        "profefe.com/path": "/debug/pprof"
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: quay.io/influxdb/influxdb:2.0.0-alpha
        ports:
        - containerPort: 9999
